# Generated by Django 5.2 on 2025-05-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('tax_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='learning_plan',
            field=models.TextField(default='Теми ще не додано', verbose_name='Короткий опис тем'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=300000000000, max_length=20),
            preserve_default=False,
        ),
    ]
